### ISSUE TITLE
Setup Streamlit sharing

### ISSUE THREAD

**Issue by SteinsGate9** [CMU-IDS-2021/assignment-2-05839-benson#1]
Dear TAs, please add our repo to Streamlit sharing and then respond to this issue with the URL to the deployed application.

we could run this repo locally by running "streamlit run main.py", but we still have a few questions regarding the data source.
1) do we need to upload data to github to make it work in Streamlit sharing ?
2) is git lfs an option to push data to github and use it in Streamlit ?

**Comment by kunalkhadilkar** [comment]
https://share.streamlit.io/cmu-ids-2021/assignment-2-05839-benson/main.py

I don't think you can use git lfs to push data to Streamlit. Please post these on Piazza and Adam will be able to explain in more detail.
